/**
 * Cursor Agent Export Adapter.
 * Spec reference: SPEC-open-studio.md Section 7.3.
 *
 * Splits System Rules vs. User Task for dual-clipboard workflows, and produces
 * downloadable .cursorrules, .cursor/rules/open-studio.mdc, and prompt.xml.
 */

import type { CompiledPromptResult, ComposerConfig } from "../composer/composer-types"
import type { AgentExportPackage, DownloadableFile, IAgentExporter } from "./export-types"

export class CursorExporter implements IAgentExporter {
  readonly agentName = "cursor" as const

  formatExport(result: CompiledPromptResult, config: ComposerConfig): AgentExportPackage {
    const primaryClipboardText = this.buildSystemRules(result)
    const secondaryClipboardText = this.buildUserTask(result, config)

    const cursorrulesContent = this.buildCursorrules(result, config)
    const mdcContent = this.buildMdcRule(result, config)

    const downloadableFiles: readonly DownloadableFile[] = [
      {
        filename: ".cursorrules",
        mimeType: "text/plain",
        content: cursorrulesContent,
      },
      {
        filename: ".cursor/rules/open-studio.mdc",
        mimeType: "text/markdown",
        content: mdcContent,
      },
      {
        filename: "prompt.xml",
        mimeType: "application/xml",
        content: result.fullPrompt,
      },
    ]

    return {
      primaryClipboardText,
      secondaryClipboardText,
      downloadableFiles,
    }
  }

  private buildSystemRules(result: CompiledPromptResult): string {
    return result.systemPromptBlock
  }

  private buildUserTask(result: CompiledPromptResult, config: ComposerConfig): string {
    const l9 = config.layer9BriefAndClarification
    if (
      !l9.userObjective.trim() &&
      l9.featureRequirements.length === 0 &&
      l9.clarificationAnswers.length === 0
    ) {
      return ""
    }
    if (result.userPromptBlock.trim().length > 0) {
      return result.userPromptBlock.trim()
    }
    const parts: string[] = []
    if (l9.userObjective.trim()) {
      parts.push(l9.userObjective.trim())
    }
    if (l9.featureRequirements.length > 0) {
      parts.push("\nRequirements:\n" + l9.featureRequirements.map((r) => `- ${r}`).join("\n"))
    }
    return parts.join("\n")
  }

  private buildCursorrules(result: CompiledPromptResult, config: ComposerConfig): string {
    const l3 = config.layer3AuthoritativeConstraints
    const l5 = config.layer5BrandContract
    const l8 = config.layer8UserMemory

    const hardRules = l3.enabled && l3.strictHardRules.length > 0
      ? [
          "",
          "## Hard Constraints",
          ...l3.strictHardRules.map((r) => `- ${r}`),
        ].join("\n")
      : ""

    const persistentDirectives = l8.enabled && l8.persistentDirectives.length > 0
      ? [
          "",
          "## Persistent Directives",
          ...l8.persistentDirectives.map((d) => `- ${d}`),
        ].join("\n")
      : ""

    const negativeConstraints = l8.enabled && l8.negativeConstraints.length > 0
      ? [
          "",
          "## Negative Constraints",
          ...l8.negativeConstraints.map((c) => `- ${c}`),
        ].join("\n")
      : ""

    return [
      "# Open Studio Cursor Rules",
      "<!-- Automatically generated by Open Studio -->",
      "",
      "You are an expert frontend engineer following the Open Studio design contract.",
      "",
      "## Architecture & Stack",
      `- Framework: ${l3.targetFramework}`,
      `- CSS Engine: ${l3.cssEngine}`,
      `- Viewport: ${l3.viewport}`,
      `- Design System: ${l5.selectedSystemId ?? "default"}`,
      hardRules,
      persistentDirectives,
      negativeConstraints,
      "",
      "## System Directives",
      result.systemPromptBlock,
    ]
      .filter((line) => line !== "")
      .join("\n")
  }

  private buildMdcRule(result: CompiledPromptResult, config: ComposerConfig): string {
    const l3 = config.layer3AuthoritativeConstraints
    const l5 = config.layer5BrandContract
    const l8 = config.layer8UserMemory

    const hardRules = l3.enabled && l3.strictHardRules.length > 0
      ? [
          "",
          "### Hard Constraints",
          ...l3.strictHardRules.map((r) => `- ${r}`),
        ].join("\n")
      : ""

    const persistentDirectives = l8.enabled && l8.persistentDirectives.length > 0
      ? [
          "",
          "### Persistent Directives",
          ...l8.persistentDirectives.map((d) => `- ${d}`),
        ].join("\n")
      : ""

    return [
      "---",
      "description: Open Studio Design System & Architecture Directives",
      "globs: *",
      "alwaysApply: true",
      "---",
      "",
      "# Open Studio Design System & Architecture Directives",
      "",
      "Follow these design guidelines, design tokens, and engineering constraints:",
      "",
      "## Tech Stack & Constraints",
      `- Framework: ${l3.targetFramework}`,
      `- Styling: ${l3.cssEngine}`,
      `- Active System: ${l5.selectedSystemId ?? "default"}`,
      hardRules,
      persistentDirectives,
      "",
      "## System Rules Block",
      "```xml",
      result.systemPromptBlock,
      "```",
    ]
      .filter((line) => line !== "")
      .join("\n")
  }
}

export const cursorExporter = new CursorExporter()
